# Generated by Django 3.1.14 on 2022-04-07 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sender', models.IntegerField(blank=True, default='', max_length=10)),
                ('receiver', models.TextField()),
                ('amount', models.FloatField(default=False)),
            ],
        ),
    ]
